name: 'NRF Connect SDK CI action v2.6.1'
description: 'Building nrf connect sdk projects'
branding:
  color: blue
  icon: Link
inputs:
  board:  # id of input
    description: 'Board for build'
    required: true
  build_dir:
    description: 'Building directory'
    required: true
    default: 'build'
runs:
  using: 'docker'
  image: 'docker://parthsanepara/nrf-connect-sdk:v2.6.1'
  args:
    - west 
    - build
    - --build-dir 
    - ${{ inputs.build_dir }}
    - .
    - --pristine
    - --no-sysbuild
    - --board 
    - ${{ inputs.board }}
    
