name: 'NRF Connect SDK CI action'
description: 'Building nrf connect sdk projects'
branding:
  color: blue
  icon: Link
inputs:
  board:  # id of input
    description: 'Board for build'
    required: true
  build_dir:
    description: 'Building directory'
    required: true
    default: 'build'
  sysbuild:
    description: 'Use sysbuild (true/false)'
    required: false
    default: 'false'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/jonathansmithinfact/nrf-connect-sdk-ci:v3.0.2'
    

